### PR TITLE
Build lib using cmake

### PR DESCRIPTION
**Pull request by albertopasqualetto**
This solves build failures in windows, i've also tested this in ubuntu wsl

### CODE REVIEW

**Comment by duncaneddy** [comment]
Really appreciate the work on this PR and getting it to build on windows—this request comes up periodically so I know will be appreciated!

Let me take some time this evening to check out the build process locally to confirm it works on MacOS and Linux environments still and then will merge.

**Comment by albertopasqualetto** [comment]
Good (I make you know that the repo on which I rely to build with cmake is not popular, but the owner i really active)

**Comment by duncaneddy** [comment]
So long as the package is stable, and integrates well cross platform so ultimately all that is needed is just a `pip install pysofa2` and that it just works I think we're good.

I'd prefer if that the user doesn't need to explicitly install CMake, but have the dependencies take care of any requirements needed to build the package so that doing a `pip install pysofa2` "just works". But I'll need to educate myself on the package. It's not a show-stopper if it's required though given the wide support and adoption of CMake.

**Comment by albertopasqualetto** [comment]
Cmake is supposed to be automatically installed during the build process.

**Comment by duncaneddy** [comment]
So it installs perfectly, though I'm now encountering the following error when I attempt to `import pysofa2` on either Linux or MacOS. Going to try to do some additional debugging to see why it isn't being discovered. I see the `.dylib` and `.so` being built. but not sure it's being properly bundled with the rest of the library.

```
import pysofa2
/Users/duncan/repos/Space/pysofa2/pysofa2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/duncan/repos/Space/pysofa2/pysofa2/__init__.py", line 3, in <module>
    from pysofa2.sofa_wrapper import *
  File "/Users/duncan/repos/Space/pysofa2/pysofa2/sofa_wrapper.py", line 21, in <module>
    raise ImportError('Unable to find the shared C library "pysofa2._sofa_c".')
ImportError: Unable to find the shared C library "pysofa2._sofa_c".
```

**Comment by duncaneddy** [comment]
I just pushed a new commit that slightly changes how the output compiled library is searched for. This fixes the import on Linux and MacOS, and would like to confirm that it still works for windows builds as well before merging.

**Comment by albertopasqualetto** [comment]
```
>>> import pysofa2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alber\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\pysofa2\__init__.py", line 3, in <module>
    from pysofa2.sofa_wrapper import *
  File "C:\Users\alber\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\pysofa2\sofa_wrapper.py", line 20, in <module>
    raise ImportError('Unable to find the shared C library "pysofa2._sofa_c".')
ImportError: Unable to find the shared C library "pysofa2._sofa_c"
```

No, it does not work neither on windows and on ubuntu wsl on my side. I think it was correct as it was before since the the folders are:
on Windows:
```
__about__.py
__init__.py
__pycache__
_sofa_c.dll
_sofa_c.lib
sofa.h
sofa_wrapper.py
sofam.h
```

on Linux:
```
__about__.py
__init__.py
__pycache__
_sofa_c.so
sofa.h
sofa_wrapper.py
sofam.h
```

The `.py-build-cmake_cache` folder should be only used during build and then the files should be "installed" in the python `site-packages` folder

**Comment by duncaneddy** [comment]
Hmm... ok when I was doing the installation on windows or mac the `_sofa_c.*` library isn't getting copied to the package root in `site-packages` but instead being left in the `.py-build-cmake_cache` so when I attempt to import the package it doesn't find the necessary library and errored out.

I'll see if it's something with how I was doing the package installation.

**Comment by duncaneddy** [comment]
Yup it looks like this was on my installation process. It seems like installing with `pip install .` doesn't work.

Reverted the commit and merging. Will cut a release on pypi.

**Pull request merged**
